;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	haskell-indentation-delete-char
	icicle-yank-maybe-completing
	smart-beginning-of-line
	))

(setq mc/cmds-to-run-once
      '(
	haskell-indentation-delete-backward-char
	icicle-goto-marker-or-set-mark-command
	))
